### PR TITLE
macOS build/run support

### PR DESCRIPTION
**Pull request by atipls**
Since the build system already uses clang, compiling it on my M1 MacBook Air was relatively easy.
These are the changes I had to make for a successful build.

After these changes, building was done with:
`LD=ld.lld arch -x86_64 make` 

However, it triple faults on boot.

### CODE REVIEW

**Comment by iProgramMC** [comment]
It triple faults on boot? That's strange, I haven't had that issue before. Are you able to send a compiled executable and a QEMU register dump at the time of the triple fault? (so run with `-d cpu_reset`, then use telnet or something to copy the registers from the qemu console)

**Comment by atipls** [comment]
The crash happens in vsnprintf, early return-hacking it out gets to a "boot" screen.

QEMU Register dump of the triple fault:
```Triple fault
CPU Reset (CPU 0)
EAX=00103b32 EBX=00103b32 ECX=c054a53c EDX=00000457
ESI=c0548520 EDI=c0040000 EBP=c05484f4 ESP=c0548490
EIP=c010b12c EFL=00000086 [--S--P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 00000000 ffffffff 00cf9a00 DPL=0 CS32 [-R-]
SS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
DS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
GS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
LDT=0000 00000000 00000000 00008200 DPL=0 LDT
TR =0000 00000000 0000ffff 00008b00 DPL=0 TSS32-busy
GDT=     c01473aa 00000093
IDT=     00000000 000003ff
CR0=80010013 CR2=00000040 CR3=00324000 CR4=00000600
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=ffff0ff0 DR7=00000400
CCS=00000058 CCD=c0548490 CCO=SUBL
EFER=0000000000000000
FCW=037f FSW=0000 [ST=0] FTW=00 MXCSR=00001f80
FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
XMM00=0000000000000000 0000000000000000 XMM01=0000000000000000 0000000000000000
XMM02=0000000000000000 0000000000000000 XMM03=000000000
```

image

**Comment by iProgramMC** [comment]
Yikes! Are you able to send me the NanoShell image that triple faults so that I can look into it? I don't get this error on my end

**Comment by atipls** [comment]
GitHub doesn't like uploading bin/iso files, but I can provide them through Matrix/Discord if available.

Also note that I'm using clang that comes with Xcode (Apple clang version 14.0.0 (clang-1400.0.29.102), Ventura beta) which might be the cause.

**Comment by iProgramMC** [comment]
Yeah, sure, I'm in the OSdev Discord, you can DM me the file. (I remember seeing you there) Otherwise, iProgramInCpp#8900

**Comment by iProgramMC** [comment]
Okay, tracked it down to a subsection of `.rodata` not being properly held within the 3 GiB range (so it was located at `0x00100000` rather than `0xC0100000`. :)

**Pull request merged**
