### PR TITLE
Added Linux Support

### PR DESCRIPTION
**Pull request by mine-man3000**

### CODE REVIEW

**Comment by mine-man3000** [comment]
accidently left the compiled stuff in this. oops

**Comment by iProgramMC** [comment]
Hi,

Thanks for your pull request.  Unfortunately I don't think I can merge this, here's why:
1) Where do I get `i686-elf-gcc`?
2) You removed a _tooooon_ of code, it seems to me like you worked with an earlier version.

I'll be making my own linux support to work with the latest version.

**Comment by mine-man3000** [comment]
I got the gcc from the same place you did I just got the linux version instead. I didn't touch the code at all (except for my python stuff, and replacing the initramfs thing in the Makefile) so I must've used an outdated version. Also what is the `tools_src/fsmaker` for? I tried to read it but without the proper Windows headers I couldn't understand it properly

**Comment by iProgramMC** [comment]
You're using V0.20 in your commit whilst NanoShell is on V0.30.

Also fsmaker takes all the files in the fs/ directory and assembles them in the `nanoshell_initrd`. You could also make a placeholder initrd with nothing inside, but I prefer having some files in the initrd by default.

**Comment by iProgramMC** [comment]
You could use `opendir()` and `readdir()` as alternatives to the win32 calls I used, too

**Comment by mine-man3000** [comment]
what is the nanoshell_initrd for? I don't know if the two things are related but if you run `make iso` in my version (which I'm currently updating to V0.30) it made a functioning iso.

**Comment by mine-man3000** [comment]
I have mostly updated everything and all I need to do is convert all the win32 calls in fsmaker to linux calls. I'll have to do it tomorrow but when I'm done I'll update my fork

**Comment by iProgramMC** [comment]
By the way, the `nanoshell_initrd` stores some read only system files (when you boot into it, you're dropped into `/`, you can do `ls` and it shows you a list of dirs with mounted drives, and the contents of the initrd)

**Comment by iProgramMC** [comment]
Thanks for your effort, appreciate it.

Because I worked with someone to add Linux build support, I'll now close your pull request.

**Pull request closed without merging**
